config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  post "auth" => "welcome#create", as: "auth"
  get 'dash' => "dashboard#index", as: "dashboard"
  get "dashout" => "welcome#logout", as: "logout"

  post "dash/msg" => "dashboard#send_message"
  post "dash/text/removed" => "dashboard#text_removed"

  post "dash/msg/remove" => "dashboard#remove_msg", as: "remove_msg"
  get "dash/text/removed/clear" => "dashboard#text_removed_clear", as: "text_removed_clear"

  post "dash/msg/image" => "dashboard#upload_img", as: "upload_img"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  scope :without_images, -> {
    where("image is null")
  }

  scope :clean, -> {
    without_images.delete_all
  }
end

app/models/removed_text.rb
class RemovedText < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :messages
  has_many :removed_texts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :logged_in?, :current_user

  def current_user
    if session[:user_id]
      @user = User.find_by_id(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to root_path unless logged_in?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authorized
  before_action :update_active_at
  require 'pusher'

  def index
    @person = User.where.not(id: @user.id).first
    @removed_texts = @person.removed_texts.order(created_at: "DESC").paginate(page: 1, per_page: 20)
    @my_removed_texts = @user.removed_texts.order(created_at: "DESC").paginate(page: 1, per_page: 20)
    @messages = Message.where("created_at>=?", Time.current-12.hour).order(created_at: "DESC").paginate(page: 1, per_page: 50)
  end

  def send_message
    return render json: { code: 404 } unless params[:encrypted_data].present?

    data = Base64.decode64(params[:encrypted_data])

    reply_for = ""
    if params[:reply_to_id].present?
     reply_msg = Message.find_by_id(params[:reply_to_id])
     reply_for = reply_msg.content
    end

    msg = @user.messages.create(content: data, reply_for: reply_for)

    send_pusher

    render json: {code: 200, message: "Send", msg: msg.content }
  end

  def text_removed
    return render json: { code: 404 } unless params[:msg].present?

    @user.removed_texts.create(content: params[:msg]) unless @user.username == "qwert"

    # prev_removed = @user.removed_texts.order(created_at: "DESC").first

    # prev_text = prev_removed&.content

    # unless prev_text.to_s.include?(params[:msg])
    #   @user.removed_texts.create(content: params[:msg])
    # end

    render json: { code: 200, message: "saved" }
  end

  def text_removed_clear
    if params[:guest].present?
      @person = User.where.not(id: @user.id).first
      @person.removed_texts.order(created_at: "DESC").paginate(page: 1, per_page: 20).destroy_all
    else
      @user.removed_texts.destroy_all
    end
    redirect_to dashboard_path
  end

  def remove_msg
    if params[:from].present? && params[:to].present?
      @user.messages.where("id >= ? and id <=?", params[:from], params[:to]).destroy_all
    end
    redirect_to dashboard_path
  end

  def upload_img
    if params[:image].present?
      cloud = Cloudinary::Uploader.upload(params[:image], folder: @user.username)
      msg = @user.messages.create(content: "Image", image: cloud["secure_url"])
      send_pusher
    end
    redirect_to dashboard_path
  end

  protected
  def update_active_at
    @user.update(last_updated_at: Time.now)
  end

  def send_pusher
    @person = User.where.not(id: @user.id).first

    pusher = Pusher::Client.new(
      app_id: '1837761',
      key: '268265a228eff4a444d7',
      secret: '783930a173d076704261',
      cluster: 'ap2',
      encrypted: true
    )

    pusher.trigger("my-channel-#{@person.id}", "my-event", {
      message: 'new'
    })
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def create
    @user = User.find_by_username(params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else  
      redirect_to root_path
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def linkify(text)
    return text unless text.to_s.present?

    URI.extract(text, ['http', 'https']).uniq.each do |url|
      sub_text = "<a href='#{url}' class='message-link' target='_blank'>#{url}</a>"
      text.gsub!(url, sub_text)
    end
    text.html_safe
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/_chat.html.erb
<div class="hidden" id="chat-modal">
  <div class="inset-0 transition-opacity" aria-hidden="true"></div>

  <div class="inset-0 z-10 w-screen overflow-y-auto">

    <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
      <div class="relative transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
        <div class="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
          <%= form_for :file, url: upload_img_path, html: { multipart: true } do |f| %>
            <div class="mt-1 flex max-w-md gap-x-4" data-controller="textbox">
              <label for="file-input">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-upload" viewBox="0 0 16 16">
                    <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5"/>
                    <path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708z"/>
                  </svg>

                  <input id="file-input" name="image" class="hidden" type="file" data-action="change->chats#filePreview" accept="image/*" required/>
              </label>
              <img src="" name="file" id="selected-image" width="100">
              <div id="img-btns" class="hidden">
                <div id="clear-image-btn" class="flex-none rounded-md bg-grey-200 px-3.5 py-2.5 text-sm font-semibold text-black shadow-sm hover:bg-grey-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-grey-200" data-action="click->chats#clearImg"> Clear </div>
                <hr>
                <div id="send-img"></div>
                <input type="submit" id="submit-image-btn" class="flex-none rounded-md bg-indigo-200 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-200" value="Send" data-action="click->chats#sendImage">
              </div>
            </div>
          <% end %>

          <div class="sm:flex sm:items-start">
            <div class="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-4 lg:max-w-none lg:grid-cols-2">
              <div class="mt-1 flex max-w-md gap-x-4" data-controller="textbox">
                <textarea id="text-message" required="true" name="message" autocomplete="off" rows="2" class="min-w-0 flex-auto rounded-md border-0 bg-white/5 px-3.5 py-2 text-gray-400 shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6" data-action="keyup->textbox#checkKey input->textbox#updateText"></textarea>

                <button type="submit" class="flex-none rounded-md bg-indigo-200 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-200" id="send-message" data-action="click->chats#sendMessage"><span aria-hidden="true">→</span></button>
              </div>

              <span id="reply-msg-box" class="flex items-center px-2 py-1 me-2 text-sm font-medium text-gray-800 bg-gray-100 rounded dark:bg-gray-700 dark:text-gray-300 hidden">
                <input type="hidden" id="reply-to-id">
                <div id="reply-to"></div>
                <button type="button" class="inline-flex items-center p-1 ms-2 text-sm text-gray-400 bg-transparent rounded-sm hover:bg-gray-200 hover:text-gray-900 dark:hover:bg-gray-600 dark:hover:text-gray-300 float-right" id="remove-reply" data-action="click->chats#removeReply">
                  <svg class="w-2 h-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                  </svg>
                  <span class="sr-only">X</span>
                </button>
              </span>
              
              <%= turbo_frame_tag "messages_list" do %>
                <small class="text-right">⏱️ <%=@person.last_updated_at.present? ? time_ago_in_words(@person.last_updated_at) : 'N/A'%> ago </small>
                <div class="max-w-xl lg:max-w-lg max-h-80 overflow-y-scroll overflow-x-hidden" id="message-container">
                  <% @messages.each do |msg| %>
                    <div class="flex items-start mt-1" attr-msg="msg-time-<%=msg.id%>" data-action="click->chats#messageTimestamp">
                       <div class="flex flex-col w-full max-w-[320px] leading-1.5 p-1 border-gray-200 bg-gray-<%= msg.user_id == @user.id ? '20 text-right' : '100'%> rounded-e-xl rounded-es-xl dark:bg-gray-700">
                          <div class="text-sm font-normal text-gray-900 dark:text-white">
                            <% if msg.reply_for.present? %>
                              <span class="text-gray-500 bg-gray-40 rounded dark:bg-gray-700 dark:text-gray-300">
                                ➦ <%=linkify(msg.reply_for)%>
                              </span><br>
                            <% end %>
                            <% if msg.image.present? %>
                              <span id="msg-content-<%=msg.id%>" class="<%= msg.user_id == @user.id ? 'float-right' : '' %>" data-modal-target="image-modal-<%=msg.id%>" data-action="click->chats#openImageModal"> 
                                <%#=linkify(msg.content)%>
                                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                                  <path fill-rule="evenodd" d="M13 10a1 1 0 0 1 1-1h.01a1 1 0 1 1 0 2H14a1 1 0 0 1-1-1Z" clip-rule="evenodd"/>
                                  <path fill-rule="evenodd" d="M2 6a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v12c0 .556-.227 1.06-.593 1.422A.999.999 0 0 1 20.5 20H4a2.002 2.002 0 0 1-2-2V6Zm6.892 12 3.833-5.356-3.99-4.322a1 1 0 0 0-1.549.097L4 12.879V6h16v9.95l-3.257-3.619a1 1 0 0 0-1.557.088L11.2 18H8.892Z" clip-rule="evenodd"/>
                                </svg>
                              </span>
                              <%= render partial: 'image', locals: { msg: msg } %>
                            <%else%>
                              <span id="msg-content-<%=msg.id%>"> <%=linkify(msg.content)%></span> 
                            <%end%>

                            <small id="msg-time-<%=msg.id%>" class="hidden">
                              (<%=msg.id%>) <%=time_ago_in_words(msg.created_at)%> ago 

                              <button type="button" class="inline-flex items-center p-1 ms-2 text-sm text-gray-400 bg-transparent rounded-sm hover:bg-gray-200 hover:text-gray-900 dark:hover:bg-gray-600 dark:hover:text-gray-300 float-right" id="add-reply" data-action="click->chats#addReply" attr-msg-id="<%=msg.id%>">
                                Reply
                                <span class="sr-only">Reply</span>
                              </button>
                            </small>
                          </div>
                       </div>
                    </div>
                  <%end%>
                </div>
              <%end%>
            </div>
          </div>
        </div>
        <div class="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
          <button type="button" class="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:mt-0 sm:w-auto" data-action="click->chats#closeModal">Cancel </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_image.html.erb
 <!-- Full Screen Modal -->
<div id="image-modal-<%=msg.id%>" attr-modal="image-modal-<%=msg.id%>" data-action="click->chats#closeImageModal" class="fixed inset-0 flex items-center justify-center bg-gray-900 bg-opacity-75 hidden">
  <div class="bg-white w-full h-full flex flex-col">
    <div class="p-4 border-b flex justify-between items-center" >
      <button class="text-gray-500 hover:text-gray-700" >Close</button>
    </div>
    <div class="flex-grow p-4 overflow-auto">
      <!-- Modal content -->
      <img src="<%=msg.image%>" style="width: 100%;">
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div data-controller="chats">
<div class="bg-white">
  <div class="mx-auto max-w-7xl py-16 sm:px-6 sm:py-32 lg:px-8">
    <div class="relative isolate overflow-hidden bg-gray-900 px-6 pt-16 shadow-2xl sm:rounded-3xl sm:px-16 md:pt-24 lg:flex lg:gap-x-20 lg:px-24 lg:pt-0">
      <svg viewBox="0 0 1024 1024" class="absolute left-1/2 top-1/2 -z-10 h-[64rem] w-[64rem] -translate-y-1/2 [mask-image:radial-gradient(closest-side,white,transparent)] sm:left-full sm:-ml-80 lg:left-1/2 lg:ml-0 lg:-translate-x-1/2 lg:translate-y-0" aria-hidden="true">
        <circle cx="512" cy="512" r="512" fill="url(#759c1415-0410-454c-8f7c-9a820de03641)" fill-opacity="0.7" />
        <defs>
          <radialGradient id="759c1415-0410-454c-8f7c-9a820de03641">
            <stop stop-color="#7775D6" />
            <stop offset="1" stop-color="#E935C1" />
          </radialGradient>
        </defs>
      </svg>
      <div class="mx-auto max-w-md text-center lg:mx-0 lg:flex-auto lg:py-32 lg:text-left">
        <h2 class="text-3xl font-bold tracking-tight text-white sm:text-4xl">Boost your productivity.<br>Start using our app today with <%=@user.username%></h2>
        <p class="mt-6 text-lg leading-8 text-gray-300">Visually-stunning, easy to customize site templates built with React and Next.js. The perfect starting point for your next project and the ultimate resource for learning how experts build real websites with Tailwind CSS. 
          <%= @person.last_updated_at.present? ? time_ago_in_words(@person.last_updated_at) : 'N/A'%>
        </p>
        <div class="mt-10 flex items-center justify-center gap-x-6 lg:justify-start">
          <a href="<%=logout_path%>" class="rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white">Backout</a>
          <div class="text-sm font-semibold leading-6 text-white" data-action="click->chats#openModal" id="good-link"> Expertise </div>
        </div>
      </div>
      <div class="relative mt-16 h-80 lg:mt-8">
        <img class="absolute left-0 top-0 w-[57rem] max-w-none rounded-md bg-white/5 ring-1 ring-white/10" src="https://tailwindui.com/img/component-images/dark-project-app-screenshot.png" alt="App screenshot" width="1824" height="1080">
      </div>
    </div>
  </div>
</div>
<%=render partial: "chat"%>

<div class="bg-white py-16 sm:py-32">
  <div class="mx-auto max-w-7xl">
    <img src="/assets/<%=["scooter.gif", "scooter2.png", "books.gif", "lap.gif"].sample%>" style="width: 100%;">
  </div>
</div>

<div class="bg-white py-16 sm:py-32">
  <div class="mx-auto max-w-7xl px-6 lg:px-8">
    <dl class="grid grid-cols-1 gap-x-8 gap-y-16 text-center lg:grid-cols-3">
      <div class="mx-auto flex max-w-xs flex-col gap-y-4">
        <dt class="text-base leading-7 text-gray-600">Transactions every 24 hours</dt>
        <dd class="order-first text-3xl font-semibold tracking-tight text-gray-900 sm:text-5xl">44 million</dd>
      </div>
      <div class="mx-auto flex max-w-xs flex-col gap-y-4">
        <dt class="text-base leading-7 text-gray-600">Assets under holding</dt>
        <dd class="order-first text-3xl font-semibold tracking-tight text-gray-900 sm:text-5xl">$119 trillion</dd>
      </div>
      <div class="mx-auto flex max-w-xs flex-col gap-y-4" data-action="click->chats#openRemoved">
        <dt class="text-base leading-7 text-gray-600">New users annually</dt>
        <dd class="order-first text-3xl font-semibold tracking-tight text-gray-900 sm:text-5xl">46,000</dd>
      </div>
    </dl>
  </div>

  <div id="removed-text" class="mx-auto max-w-7xl px-6 lg:px-8 bg-white text-left text-gray-300 hidden">
  <% if @user.username == "qwert" %>
    Gone ME <a href="<%=text_removed_clear_path()%>">Remove all</a>: <br>
      <% if @my_removed_texts.present? %>
        <% @my_removed_texts.each_with_index do |text,ind| %>
          <%=ind+1%> : <%=text.content%> (<%= time_ago_in_words(text.created_at) %>)<br>
        <%end%>
      <% else %>
        N/A
      <% end %>
    <br><br>

    Gone Guest <a href="<%=text_removed_clear_path(guest: "yes")%>">Remove all</a>: <br>
    <% if @removed_texts.present? %>
      <% @removed_texts.each_with_index do |text,ind| %>
        <%=ind+1%> : <%=text.content%> (<%= time_ago_in_words(text.created_at) %>)<br>
      <%end%>
    <% else %>
      N/A
    <% end %>
    <br><br>
    Clear: <br>

    <%=form_for :remove_msg, url: remove_msg_path do |f|%>
      <div class="flex">
        <input type="text" required autocomplete="off" name="from" placeholder="From" class="flex-shrink-0 z-10 inline-flex items-center py-2.5 px-4 text-sm font-medium text-center text-gray-900 bg-gray-100 border border-e-0 border-gray-300 dark:border-gray-700 dark:text-white rounded-s-lg hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800">

        <div class="relative w-full">
          <input type="text" required name="to" placeholder="To" class="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-e-lg rounded-s-gray-100 rounded-s-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:border-blue-500">

          <input type="submit" value="Go" class="absolute top-0 end-0 p-2.5 h-full text-sm font-medium text-white bg-blue-700 rounded-e-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        </div>
      </div>
    <% end %>

  <% end %>
</div>
</div>

</div>

app/views/welcome/index.html.erb
<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <h2 class="sr-only">Products</h2>

    <div class="grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
      <a href="#" class="group">
        <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-lg bg-gray-200 xl:aspect-h-8 xl:aspect-w-7">
          <img src="https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-01.jpg" alt="Tall slender porcelain bottle with natural clay textured body and cork stopper." class="h-full w-full object-cover object-center group-hover:opacity-75">
        </div>
        <h3 class="mt-4 text-sm text-gray-700">Earthen Bottle</h3>
        <p class="mt-1 text-lg font-medium text-gray-900">$48</p>
      </a>
      <a href="#" class="group">
        <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-lg bg-gray-200 xl:aspect-h-8 xl:aspect-w-7">
          <img src="https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-02.jpg" alt="Olive drab green insulated bottle with flared screw lid and flat top." class="h-full w-full object-cover object-center group-hover:opacity-75">
        </div>
        <h3 class="mt-4 text-sm text-gray-700">Nomad Tumbler</h3>
        <p class="mt-1 text-lg font-medium text-gray-900">$35</p>
      </a>
      <a href="#" class="group">
        <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-lg bg-gray-200 xl:aspect-h-8 xl:aspect-w-7">
          <img src="https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-03.jpg" alt="Person using a pen to cross a task off a productivity paper card." class="h-full w-full object-cover object-center group-hover:opacity-75">
        </div>
        <h3 class="mt-4 text-sm text-gray-700">Focus Paper Refill</h3>
        <p class="mt-1 text-lg font-medium text-gray-900">$89</p>
      </a>
      <a href="#" class="group">
        <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-lg bg-gray-200 xl:aspect-h-8 xl:aspect-w-7">
          <img src="https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-04.jpg" alt="Hand holding black machined steel mechanical pencil with brass tip and top." class="h-full w-full object-cover object-center group-hover:opacity-75">
        </div>
        <h3 class="mt-4 text-sm text-gray-700">Machined Mechanical Pencil</h3>
        <p class="mt-1 text-lg font-medium text-gray-900">$35</p>
      </a>
    </div>

    <div class="text-center">
        <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">Data to enrich your online business</h1>
        <p class="mt-6 text-lg leading-8 text-gray-600">Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua.</p>
        <div class="mt-10 flex items-center justify-center gap-x-6">
          <%=form_for :login, url: auth_path do |f|%>

            <div class="flex">
              <input type="text" autocomplete="off" id="uname" name="username" placeholder="UID" class="flex-shrink-0 z-10 inline-flex items-center py-2.5 px-4 text-sm font-medium text-center text-gray-900 bg-gray-100 border border-e-0 border-gray-300 dark:border-gray-700 dark:text-white rounded-s-lg hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800">

              <div class="relative w-full">
                <input id="pass" type="password" name="password" placeholder="KEY" class="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-e-lg rounded-s-gray-100 rounded-s-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:border-blue-500">

                <input type="submit" value="Price" class="absolute top-0 end-0 p-2.5 h-full text-sm font-medium text-white bg-blue-700 rounded-e-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
              </div>
            </div>
          <% end %>

        </div>
      </div>
  </div>
</div>